#!/usr/bin/env python3
"""Visual Director Layer (Phase 5).
Builds planning/visual_scene_plan.json from the master-audio transcript.
Scene boundaries are snapped to the 1/60 s frame grid (60 fps output).
Events carry absolute word-anchored times = the word-level event map.
"""
import json
from pathlib import Path

PROJECT = Path("/home/z/my-project/project")
TR = json.load(open(PROJECT / "transcript" / "transcript_timestamps.json"))
TOTAL_AUDIO = TR["source_audio"]["duration"]  # 779.36

FPS = 60.0

# (start, end, title, concept, [ (abs_time, word_anchor, visual_event) ])
SCENES = [
    (0.00, 19.50, "Football Analogy", "Many decision-makers share one field",
     [(0.00, "football match", "Pitch fades in, center line + circle draw, chip ONE GROUND"),
      (1.82, "rules are the same", "Chip RULES SAME pulses"),
      (4.18, "20 players", "10 blue + 10 orange player dots pop in around formation"),
      (6.20, "decision", "Focus player highlighted, chip DECISION above"),
      (8.06, "teammates and opponents", "Dashed sight-lines to 2 teammates (blue) and 2 opponents (orange)"),
      (11.26, "pass", "Ball dot travels blue-to-blue along pass arrow"),
      (14.14, "cover positions", "Cover arc lines appear behind focus pair"),
      (17.04, "team result", "Score chip TEAM RESULT +1 with rising arrow")]),
    (19.50, 25.84, "Players Become Programs", "Bridge from football to MARL",
     [(19.50, "imagine", "Small pitch icon on left"),
      (21.20, "computer programs", "Pitch icon morphs into terminal panel with AGENT code lines"),
      (22.64, "multi-agent reinforcement learning begins", "Big label MARL writes in with accent underline")]),
    (25.84, 46.22, "Reinforcement Learning Loop", "Agent-environment action-reward cycle",
     [(25.84, "agent", "AGENT panel top, ENVIRONMENT panel bottom"),
      (31.40, "environment", "Environment panel fills with grid + obstacle dots"),
      (35.74, "information", "Arrow env-to-agent labeled OBSERVATION"),
      (37.20, "chooses action", "Arrow agent-to-env labeled ACTION fires"),
      (39.32, "reward or penalty", "Green +R token and red -R token fly back along feedback path"),
      (42.10, "gradually learns", "Loop arrows pulse, chip LEARNING loops at right")]),
    (46.22, 58.90, "Maze to Many Agents", "From single agent to MARL",
     [(46.22, "robot is in the maze", "5x5 maze grid left, robot dot enters"),
      (48.50, "reward", "Path approaches exit flag, +1 bubble"),
      (50.50, "penalty", "Wall hit flash red, -1 bubble"),
      (52.08, "lot of agents", "Two more robot dots spawn in maze"),
      (55.08, "multi-agent reinforcement learning", "Chip MARL ties robots together with links")]),
    (58.90, 81.84, "Policy and Shared World", "Observations, policy, other agents",
     [(58.90, "observations", "Three agent nodes around env panel, eye icons feed in"),
      (61.50, "takes action according to their policy", "Action arrows out of each agent"),
      (64.32, "policy", "Card POLICY with mini rule IF s THEN a"),
      (69.18, "other agents are also taking actions", "Neighbor agent arrows fire, env contents shuffle"),
      (72.30, "environment is changing", "Env panel dots rearrange"),
      (78.58, "other intelligent agents", "Purple arrow from neighbor agent into focus agent")]),
    (81.84, 100.14, "Shared Space", "Space, resources, rules",
     [(81.84, "space, resources or rules", "Two mini panels: warehouse, road"),
      (86.64, "warehouse", "Warehouse aisle with racks, one shared aisle highlighted"),
      (89.62, "same roads", "Road strip with two cars nose-to-tail"),
      (91.68, "same charging station", "Two robot paths converge on bolt icon"),
      (94.40, "competition", "Red spark, chip COMPETITION"),
      (95.88, "different routes", "Paths split to two packages"),
      (98.52, "cooperation", "Green check, chip COOPERATION")]),
    (100.14, 118.84, "Cooperation vs Competition", "Common goal vs opposite goals",
     [(100.14, "cooperation", "Left panel COOPERATION with shared target ring"),
      (102.60, "rescue drones", "Three drone icons fan over map regions"),
      (105.40, "own route", "Each drone gets dashed route"),
      (107.12, "team objective", "One team ring around all routes"),
      (108.46, "competition", "Right panel COMPETITION"),
      (111.76, "chess", "Mini chess board, pieces clash, W and L tags"),
      (114.40, "same resources", "Two bases linked to one contested resource hex")]),
    (118.84, 141.88, "Non-Stationarity", "Environment changes as others learn",
     [(118.84, "predict the opponent", "Two policy cards face off, eye arrow between"),
      (122.50, "policy can fail", "Red crack across left card"),
      (127.90, "non-stationary", "Background grid starts sliding, chip NON-STATIONARY"),
      (131.22, "also changing", "Cards flip DEFENSE v1 to v2, ATTACK v1 to v2"),
      (135.54, "changes attack", "Right card morphs again"),
      (139.64, "makes others better", "Mutual level-up arrows loop between cards")]),
    (141.88, 149.02, "Mixed Motives", "Cooperate and compete at once",
     [(141.88, "both", "Two blue dots and two orange dots"),
      (145.26, "teammates cooperate", "Green link between blue pair"),
      (146.60, "compete against opposing team", "Red cross-links between teams")]),
    (149.02, 173.34, "Credit Assignment", "Who contributed to the team reward?",
     [(149.02, "credit assignment", "Question chip TEAM REWARD: WHO CONTRIBUTED?"),
      (157.56, "four robots", "Four robot nodes around a heavy box"),
      (161.44, "team got a reward", "Box slides to destination flag, +R TEAM banner"),
      (165.10, "one gave direction", "Robot A tag DIRECTION with arrow"),
      (169.00, "pushed the box", "Robot B tag PUSH, box nudge"),
      (170.00, "cleared the way", "Robot C tag CLEAR WAY"),
      (171.40, "doing nothing", "Robot D dims with dotted idle ring")]),
    (173.34, 199.36, "Reward Balance", "Shared vs individual rewards",
     [(173.34, "same reward", "Panel SHARED: +R copies to all four, inactive glows too"),
      (178.60, "only the pushing robot", "Panel INDIVIDUAL: +R to pusher only, direction tag greys"),
      (184.58, "both useful", "Balance scale center: pans TEAM and LOCAL"),
      (188.92, "team success", "TEAM pan dips, chip TEAM SUCCESS"),
      (191.40, "local action", "LOCAL pan dips, chip LOCAL ACTION"),
      (196.84, "selfish", "Two red mini states: SELFISH, LOST ROLE")]),
    (199.36, 217.26, "Delayed Reward", "Temporal credit assignment",
     [(199.36, "action is taken now", "Timeline bar, drone acts at NOW mark"),
      (206.06, "route first", "Drone icon flies along timeline"),
      (208.60, "after 10 minutes", "Target flag far right, +10 MIN bracket"),
      (210.36, "which decision helped", "Question marks along the gap"),
      (214.54, "temporal credit", "Chip TEMPORAL CREDIT, dashed back-arrow to NOW")]),
    (217.26, 239.62, "Feedback Gap", "Human feedback vs reward signal",
     [(217.26, "human teams", "Manager figure left"),
      (219.78, "planning was useful", "Bubbles GOOD PLAN, GOOD TIMING, WEAK COMMS"),
      (225.30, "don't get such feedback", "Agent right gets only +1 -1 tokens"),
      (227.82, "estimate contribution", "Gauge dial CONSEQUENCE?"),
      (231.68, "reward is too late", "Slow sluggish arrow, chip SLOW LEARNING"),
      (235.16, "sub-goals", "Milestone flags on path, chip SUB-GOALS")]),
    (239.62, 280.84, "Partial Observability", "Hidden info, memory, communication",
     [(239.62, "part of the environment", "Two corridor panels split by wall"),
      (245.20, "can see its corridor", "View cones from each robot, fog on far side"),
      (252.94, "hidden information", "Fog label HIDDEN"),
      (254.18, "memory and communication", "Memory card + chat bubble icons"),
      (258.84, "already been searched", "Bubble LEFT DONE with tick"),
      (262.54, "new area", "Right robot moves to fresh corridor"),
      (268.72, "guess their intentions", "Dashed observe arrow with ?"),
      (277.70, "improves the team's results", "Funnel filter chip USEFUL INFO ONLY")]),
    (280.84, 304.62, "Traffic Management", "Coordinated traffic signals",
     [(280.84, "traffic management", "Road grid with three signal nodes"),
      (287.44, "different agents", "Signals become agent dots"),
      (290.00, "observe its nearby traffic", "View cones on each signal"),
      (292.80, "signals coordinate", "Sync links between signals, green waves"),
      (296.48, "jammed on the other road", "Red congestion cluster on cross road"),
      (301.62, "smooth flow of the network", "Chip NETWORK FLOW, flow arrows turn green")]),
    (304.62, 325.98, "Warehouse Robots", "Pick, deliver, coordinate",
     [(304.62, "warehouse robots", "Rack rows, two robots, packages"),
      (307.18, "picks and delivers", "Robot A carries package to dock"),
      (309.50, "avoid busy aisles", "Busy aisle flashes, routes bend around it"),
      (313.64, "divide tasks", "Packages split between robots, tick marks"),
      (316.34, "competition", "Bolt conflict ping between two robots"),
      (320.26, "collision, deadlines, energy", "Chips NO COLLISION, DEADLINES, ENERGY")]),
    (325.98, 347.90, "Drone Coverage", "Search area division",
     [(325.98, "drones", "Large area frame, three drones"),
      (330.94, "random route", "Overlapping dashed loops"),
      (333.12, "scanned again", "Red RESCAN flashes on overlap"),
      (335.60, "observe and share", "Grid partition colors per drone"),
      (337.56, "coverage can be better", "Full grid tinted, chip COVERAGE UP"),
      (343.22, "detects an object", "Target ping on cell, other drones converge")]),
    (347.90, 370.00, "CTDE", "Centralized training, decentralized execution",
     [(347.90, "centralized training", "TRAINING panel: all agent nodes linked to GLOBAL INFO hub"),
      (353.38, "information of all the agents", "Hub collects all arrows"),
      (361.58, "local observations", "EXECUTION panel: agents standalone with sensor cones"),
      (364.38, "training room", "Map icon in training panel"),
      (367.00, "uses only its sensors", "Sensor icon in execution panel, arrow TRAINING then EXECUTION")]),
    (370.00, 392.90, "Sample Efficiency and Sim2Real", "Trials, cost, reality gap",
     [(370.00, "limitations", "Chip LIMIT 1"),
      (374.96, "lot of trials", "Trial counter spins to x1000"),
      (379.34, "expensive and risky", "Real robot with $ tag and warning"),
      (383.74, "simulation", "SIM box with many fast robot ghosts"),
      (388.62, "SIM2 real gap", "Chasm between SIM and REAL boxes, chip SIM2REAL GAP")]),
    (392.90, 405.40, "Scalability", "Interaction explosion",
     [(392.90, "scalability", "Chip LIMIT 2"),
      (393.44, "agents increases", "3 nodes mesh, then 10, then swarm"),
      (397.68, "100 agents", "100 dots swarm, link counter climbs"),
      (400.00, "behavior model can be difficult", "Chip INTERACTIONS EXPLODE, red mesh")]),
    (405.40, 412.52, "Reward Design", "Align reward with intent",
     [(405.40, "reward design", "Chip LIMIT 3, delivery robot with SPEED dial"),
      (406.40, "speed reward", "Dial cranks, robot dashes forward"),
      (407.60, "ignore safety", "Red warning SAFETY IGNORED"),
      (409.44, "align the reward", "Dial rebalances, chips SPEED and SAFETY both lit")]),
    (412.52, 433.02, "Explainability", "Understand why agents decide",
     [(412.52, "explainability", "Chip LIMIT 4"),
      (413.50, "teams are successful", "Green tick over agents"),
      (415.00, "hidden pattern", "Black box between agents and outcome with ?"),
      (422.64, "safety critical", "Shield icon, red edge"),
      (427.40, "why the decision", "Decision path arrows out of the box to engineer figure"),
      (430.00, "monitoring", "Chips COMMS RULES, ROLE POLICY, MONITORING")]),
    (433.02, 451.48, "Safety Constraints", "Safety before speed",
     [(433.02, "safety constraints", "Shield chip SAFETY FIRST"),
      (438.90, "narrow corridor", "Corridor with two robots head-on"),
      (441.00, "collision", "Red collision warning between them"),
      (442.82, "avoid collision", "Robots slow and yield, path clears"),
      (444.56, "team goals, local information and safety", "Three-pan balance GOALS, LOCAL, SAFETY")]),
    (451.48, 466.10, "Core Idea Recap", "The MARL loop in one frame",
     [(451.48, "core idea", "Question chip CORE IDEA?"),
      (454.62, "learn from observations", "Chain node OBSERVE with eye icon"),
      (458.86, "through policies", "Node ACT with policy card"),
      (460.76, "feedback from rewards", "Node REWARD with +R token"),
      (462.74, "cooperation or competition", "Node BEHAVIOR splits into green and red links")]),
    (466.10, 487.62, "Learning From Learners", "Others are part of the environment",
     [(466.10, "individual decisions and team outcome", "Two chips linked both ways"),
      (471.56, "single-agent", "Single loop diagram SELF-ENV"),
      (474.36, "other learners", "Loop plus inter-agent arrows"),
      (478.84, "cars share roads", "Icon pairs: cars, robots, drones on shared platforms"),
      (482.32, "share warehouses", "Warehouse pair link"),
      (484.50, "drones share information", "Drone pair link")]),
    (487.62, 505.66, "Intelligence or Coordination", "Closing thought",
     [(487.62, "humans and AI systems", "Human + agent icons in ONE ENVIRONMENT circle"),
      (491.10, "intelligence or better coordination", "Scale pans IQ vs COORDINATION"),
      (498.88, "smart but also cooperate", "Chips SMART and RESPONSIBLE joined by plus")]),
    (505.66, 525.74, "Team Game Roles", "Three agents, three roles",
     [(505.66, "team game", "Digital field grid"),
      (508.50, "three agents", "Nodes A, B, C spawn"),
      (510.76, "observes the opponent", "A eye line to red opponent"),
      (512.88, "safe route", "B dashed safe path"),
      (514.54, "completes the objective", "C to flag"),
      (516.72, "independently", "Paths overlap messy, red ? CONFUSION"),
      (521.44, "according to the role", "Clean color-coded paths, chip ROLES OK")]),
    (525.74, 547.86, "Roles and Rewards", "Support roles, richer rewards",
     [(525.74, "shares information", "Chip A: INFO with arrow to B"),
      (527.64, "plans a route", "Chip B: PLAN with arrow to C"),
      (529.18, "executes action", "Chip C: EXECUTE"),
      (530.90, "understand their roles", "Role ring around trio"),
      (539.40, "not only the final objective", "Extra reward chips INFO+, NO CRASH+, TIMING+")]),
    (547.86, 589.88, "Learning Stability", "Moving target problem",
     [(547.86, "learning stability", "Wavy policy line, chip STABILITY"),
      (550.52, "other agents are also updating", "Two policy cards rise alternately"),
      (555.00, "fail today", "Yesterday card flips red"),
      (560.00, "driver chooses routes", "Road net, driver dot picks route"),
      (562.68, "same route", "All dots crowd one road, SLOW tag"),
      (566.36, "another route", "Some dots shift, pattern changes"),
      (570.64, "continuously change the environment", "Tiles flip in waves"),
      (577.92, "observe other's behavior", "Chips OBSERVE, ADAPT"),
      (582.90, "opponent modeling", "Chips OPPONENT MODEL, POPULATION TRAINING")]),
    (589.88, 629.86, "Selective Communication", "Right message, right time",
     [(589.88, "central part", "Chat hub between agents"),
      (595.36, "noisy and slow", "All-to-all spaghetti links, red NOISY"),
      (600.00, "when, which agent, what", "Chips WHEN, WHOM, WHAT"),
      (606.68, "exact position", "Robot shares pin only, sensor stack dimmed"),
      (612.02, "target location and confidence", "Drone bubble TARGET 90%"),
      (618.40, "right time", "Envelope lands on timeline sweet spot"),
      (623.60, "message comes late", "Late envelope, decision crossed red"),
      (625.64, "message is wrong", "Corrupt envelope, policy card shakes"),
      (629.86, "trust, verification, cost", "Chips TRUST, VERIFY, COST")]),
    (629.86, 678.34, "Exploration and Safety", "Explore safely, then deploy",
     [(629.86, "balance", "Two panels EXPLORE vs EXPLOIT"),
      (634.52, "exploration", "Dotted new paths in explore panel"),
      (640.04, "already been useful", "Solid known path in exploit panel"),
      (644.94, "more difficult", "Ripple from robot A route hits robot B"),
      (655.86, "temporarily weak", "Team meter dips"),
      (660.88, "safe exploration", "Shield ring around trial robot"),
      (667.88, "safety limits and human supervision", "Chips SIM, LIMITS, HUMAN"),
      (674.36, "carefully deployed", "Arrow from SIM to REAL, chip DEPLOY")]),
    (678.34, 721.46, "Evaluation", "Beyond win and loss",
     [(678.34, "evaluate", "Big W/L tags dim, chip NOT ENOUGH"),
      (684.26, "team reward", "Dashboard bars: TEAM, CONTRIBUTION"),
      (689.26, "coordination quality and safety", "Bars COORDINATION, SAFETY"),
      (692.54, "waiting time", "Traffic chips SPEED, WAITING, EMERGENCY"),
      (695.80, "collisions, energy", "Warehouse chips CRASHES, ENERGY"),
      (704.44, "team won't be fair", "One robot overloaded, others idle, chip FAIRNESS"),
      (709.30, "new environments", "Shuffle icon NEW SETTINGS"),
      (715.74, "robust policy", "Shield tick chip ROBUST")]),
    (721.46, 779.37, "Future and Responsibility", "Where MARL goes next",
     [(721.46, "future", "Arc of domain chips appears"),
      (727.56, "smart factories", "Chip FACTORIES"),
      (728.50, "autonomous vehicles", "Chip VEHICLES"),
      (729.50, "healthcare coordination", "Chip HEALTHCARE"),
      (730.50, "disaster response", "Chip DISASTER"),
      (731.50, "energy", "Chip ENERGY"),
      (740.62, "responsibility", "Shield center, orbit chips PRIVACY, SAFETY, FAIRNESS, HUMAN"),
      (746.84, "objective is wrong", "Fast arrow into red X, chip WRONG GOAL"),
      (753.06, "better goals", "Chips POLICIES, GOALS, FEEDBACK, OVERSIGHT"),
      (758.90, "coordination becomes part of intelligence", "Circles INTELLIGENCE and COORDINATION merge"),
      (771.54, "smart or responsible", "Final question chip, slow fade to black")]),
]


def snap(t):
    return round(t * FPS) / FPS


def main():
    segs = TR["segments"]
    plan = {"source_audio": TR["source_audio"], "fps": int(FPS),
            "total_duration": snap(TOTAL_AUDIO + 1e-9), "scenes": []}
    for i, (s, e, title, concept, events) in enumerate(SCENES, 1):
        end = snap(TOTAL_AUDIO) if i == len(SCENES) else snap(e)
        start = snap(s)
        narr = [seg for seg in segs if seg["end"] > start + 1e-6 and seg["start"] < end - 1e-6]
        plan["scenes"].append({
            "id": i,
            "file": f"scene_{i:03d}.py",
            "class_name": f"Scene{i:03d}",
            "start": start,
            "end": end,
            "duration": round(end - start, 6),
            "title": title,
            "concept": concept,
            "narration": " ".join(n["text"] for n in narr),
            "events": [{"t_abs": round(t, 3), "t_rel": round(t - start, 3),
                        "word": w, "visual": v} for (t, w, v) in events],
        })
    out = PROJECT / "planning" / "visual_scene_plan.json"
    out.write_text(json.dumps(plan, indent=2, ensure_ascii=False))
    print(f"scenes: {len(plan['scenes'])}")
    print(f"total: {plan['total_duration']:.3f}s (audio {TOTAL_AUDIO}s)")
    print(f"check-sum durations: {sum(sc['duration'] for sc in plan['scenes']):.3f}")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
